require 'spec_helper'

module Iambic
  describe CLI do
    it 'finds violations' do
      args = []
      stdin = StringIO.new Sample.find('to_be_or_not_to_be').text
      stdout = StringIO.new
      CLI.new([], stdin, stdout).run

      stdout.string.should == <<-end_stdout
Found violations on 35 lines:

TO (T UW1) in "TO BE OR NOT TO BE THAT IS THE QUESTION"
WHETHER (W EH1 DH ER0) in "WHETHER 'TIS NOBLER IN THE MIND TO SUFFER"
FORTUNE (F AO1 R CH AH0 N) in "THE SLINGS AND ARROWS OF OUTRAGEOUS FORTUNE"
OR (AO1 R) in "OR TO TAKE ARMS AGAINST A SEA OF TROUBLES"
THEM (DH EH1 M) in "AND BY OPPOSING END THEM TO DIE TO SLEEP"
NO (N OW1) in "NO MORE AND BY A SLEEP TO SAY WE END"
ACHE (EY1 K) in "THE HEART ACHE AND THE THOUSAND NATURAL SHOCKS"
THAT (DH AE1 T) in "THAT FLESH IS HEIR TO 'TIS A CONSUMMATION"
BE (B IY1) in "DEVOUTLY TO BE WISHED TO DIE TO SLEEP"
TO (T UW1) in "TO SLEEP PERCHANCE TO DREAM AYE THERE'S THE RUB"
FOR (F AO1 R) in "FOR IN THAT SLEEP OF DEATH WHAT DREAMS MAY COME"
WHEN (W EH1 N) in "WHEN WE HAVE SHUFFLED OFF THIS MORTAL COIL"
MUST (M AH1 S T) in "MUST GIVE US PAUSE THERE'S THE RESPECT"
THAT (DH AE1 T) in "THAT MAKES CALAMITY OF SO LONG LIFE"
FOR (F AO1 R) in "FOR WHO WOULD BEAR THE WHIPS AND SCORNS OF TIME"
OPPRESSOR'S (AH0 P R EH1 S ER0 Z) in "THE OPPRESSOR'S WRONG THE PROUD MAN'S CONTUMELY"
OF (AH1 V) in "THE PANGS OF DESPISED LOVE THE LAW S DELAY"
INSOLENCE (IH1 N S AH0 L AH0 N S) in "THE INSOLENCE OF OFFICE AND THE SPURNS"
THAT (DH AE1 T) in "THAT PATIENT MERIT OF THE UNWORTHY TAKES"
WHEN (W EH1 N) in "WHEN HE HIMSELF MIGHT HIS QUIETUS MAKE"
WITH (W IH1 DH) in "WITH A BARE BODKIN WHO WOULD FARDELS BEAR"
TO (T UW1) in "TO GRUNT AND SWEAT UNDER A WEARY LIFE"
BUT (B AH1 T) in "BUT THAT THE DREAD OF SOMETHING AFTER DEATH"
UNDISCOVERED (AH2 N D IH0 S K AH1 V ER0 D) in "THE UNDISCOVERED COUNTRY FROM WHOSE BOURN"
NO (N OW1) in "NO TRAVELLER RETURNS PUZZLES THE WILL"
US (AH1 S) in "AND MAKES US RATHER BEAR THOSE ILLS WE HAVE"
THAN (DH AE1 N) in "THAN FLY TO OTHERS THAT WE KNOW NOT OF"
THUS (DH AH1 S) in "THUS CONSCIENCE DOES MAKE COWARDS OF US ALL"
OF (AH1 V) in "AND THUS THE NATIVE HUE OF RESOLUTION"
IS (IH1 Z) in "IS SICKLIED O'ER WITH THE PALE CAST OF THOUGHT"
ENTERPRISES (EH1 N T ER0 P R AY2 Z AH0 Z) in "AND ENTERPRISES OF GREAT PITCH AND MOMENT"
WITH (W IH1 DH) in "WITH THIS REGARD THEIR CURRENTS TURN AWRY"
OF (AH1 V) in "AND LOSE THE NAME OF ACTION SOFT YOU NOW"
ORISONS (AO1 R IH0 S AH0 N Z) in "THE FAIR OPHELIA NYMPH IN THY ORISONS"
BE (B IY1) in "BE ALL MY SINS REMEMBERED"
end_stdout
    end
  end
end

