require 'spec_helper'

module Iambic
  module Commands
    describe FindViolations do
      it 'finds violations' do
        stdin = StringIO.new Sample.find('to_be_or_not_to_be').text
        stdout = StringIO.new
        FindViolations.run [], stdin, stdout

        stdout.string.should == <<-end_stdout
Found violations on 26 lines:

QUESTION (K W EH1 S CH AH0 N, K W EH1 SH AH0 N) in "TO BE OR NOT TO BE THAT IS THE QUESTION"
WHETHER (W EH1 DH ER0, HH W EH1 DH ER0) in "WHETHER 'TIS NOBLER IN THE MIND TO SUFFER"
FORTUNE (F AO1 R CH AH0 N, F AO1 R CH UW0 N) in "THE SLINGS AND ARROWS OF OUTRAGEOUS FORTUNE"
TAKE (T EY1 K) in "OR TO TAKE ARMS AGAINST A SEA OF TROUBLES"
DIE (D AY1) in "AND BY OPPOSING END THEM TO DIE TO SLEEP"
NO (N OW1) in "NO MORE AND BY A SLEEP TO SAY WE END"
ACHE (EY1 K) in "THE HEART ACHE AND THE THOUSAND NATURAL SHOCKS"
CONSUMMATION (K AA2 N S AH0 M EY1 SH AH0 N) in "THAT FLESH IS HEIR TO 'TIS A CONSUMMATION"
AYE (AY1) in "TO SLEEP PERCHANCE TO DREAM AYE THERE'S THE RUB"
MUST (M AH1 S T) in "MUST GIVE US PAUSE THERE'S THE RESPECT"
CALAMITY (K AH0 L AE1 M AH0 T IY0, K AH0 L AE1 M IH0 T IY0) in "THAT MAKES CALAMITY OF SO LONG LIFE"
OPPRESSOR'S (AH0 P R EH1 S ER0 Z) in "THE OPPRESSOR'S WRONG THE PROUD MAN'S CONTUMELY"
DESPISED (D IH0 S P AY1 Z D) in "THE PANGS OF DESPISED LOVE THE LAW S DELAY"
INSOLENCE (IH1 N S AH0 L AH0 N S) in "THE INSOLENCE OF OFFICE AND THE SPURNS"
UNWORTHY (AH0 N W ER1 DH IY0) in "THAT PATIENT MERIT OF THE UNWORTHY TAKES"
MIGHT (M AY1 T) in "WHEN HE HIMSELF MIGHT HIS QUIETUS MAKE"
BARE (B EH1 R) in "WITH A BARE BODKIN WHO WOULD FARDELS BEAR"
UNDER (AH1 N D ER0) in "TO GRUNT AND SWEAT UNDER A WEARY LIFE"
UNDISCOVERED (AH2 N D IH0 S K AH1 V ER0 D) in "THE UNDISCOVERED COUNTRY FROM WHOSE BOURN"
NO (N OW1) in "NO TRAVELLER RETURNS PUZZLES THE WILL"
THUS (DH AH1 S) in "THUS CONSCIENCE DOES MAKE COWARDS OF US ALL"
RESOLUTION (R EH2 Z AH0 L UW1 SH AH0 N) in "AND THUS THE NATIVE HUE OF RESOLUTION"
PALE (P EY1 L) in "IS SICKLIED O'ER WITH THE PALE CAST OF THOUGHT"
ENTERPRISES (EH1 N T ER0 P R AY2 Z AH0 Z, EH1 N T ER0 P R AY2 Z IH0 Z, EH1 N ER0 P R AY2 Z AH0 Z, EH1 N ER0 P R AY2 Z IH0 Z, EH1 N T ER0 P R AY2 Z IH0 Z, EH1 N ER0 P R AY2 Z IH0 Z) in "AND ENTERPRISES OF GREAT PITCH AND MOMENT"
ORISONS (AO1 R IH0 S AH0 N Z) in "THE FAIR OPHELIA NYMPH IN THY ORISONS"
MY (M AY1) in "BE ALL MY SINS REMEMBERED"
        end_stdout
      end
    end
  end
end

